// Code generated by mockery v2.49.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IAuthHandler is an autogenerated mock type for the IAuthHandler type
type IAuthHandler struct {
	mock.Mock
}

// NewIAuthHandler creates a new instance of IAuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuthHandler {
	mock := &IAuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
