// Code generated by mockery v2.49.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IAuthUcase is an autogenerated mock type for the IAuthUcase type
type IAuthUcase struct {
	mock.Mock
}

// NewIAuthUcase creates a new instance of IAuthUcase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAuthUcase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAuthUcase {
	mock := &IAuthUcase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
