// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// IHttpResponseWriter is an autogenerated mock type for the IHttpResponseWriter type
type IHttpResponseWriter struct {
	mock.Mock
}

// HTTPCustomErr provides a mock function with given fields: ctx, err
func (_m *IHttpResponseWriter) HTTPCustomErr(ctx *gin.Context, err error) {
	_m.Called(ctx, err)
}

// HTTPJson provides a mock function with given fields: ctx, code, message, detail, data
func (_m *IHttpResponseWriter) HTTPJson(ctx *gin.Context, code int, message string, detail string, data interface{}) {
	_m.Called(ctx, code, message, detail, data)
}

// HTTPJsonOK provides a mock function with given fields: ctx, data
func (_m *IHttpResponseWriter) HTTPJsonOK(ctx *gin.Context, data interface{}) {
	_m.Called(ctx, data)
}

// NewIHttpResponseWriter creates a new instance of IHttpResponseWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIHttpResponseWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *IHttpResponseWriter {
	mock := &IHttpResponseWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
