// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// ILoanHandler is an autogenerated mock type for the ILoanHandler type
type ILoanHandler struct {
	mock.Mock
}

// CreateNewLoan provides a mock function with given fields: c
func (_m *ILoanHandler) CreateNewLoan(c *gin.Context) {
	_m.Called(c)
}

// GetLoanList provides a mock function with given fields: c
func (_m *ILoanHandler) GetLoanList(c *gin.Context) {
	_m.Called(c)
}

// UpdateLoanStatus provides a mock function with given fields: c
func (_m *ILoanHandler) UpdateLoanStatus(c *gin.Context) {
	_m.Called(c)
}

// NewILoanHandler creates a new instance of ILoanHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewILoanHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ILoanHandler {
	mock := &ILoanHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
