// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import (
	model "backend/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// IModel is an autogenerated mock type for the IModel type
type IModel struct {
	mock.Mock
}

// GetProps provides a mock function with no fields
func (_m *IModel) GetProps() model.ModelProps {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProps")
	}

	var r0 model.ModelProps
	if rf, ok := ret.Get(0).(func() model.ModelProps); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.ModelProps)
	}

	return r0
}

// NewIModel creates a new instance of IModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *IModel {
	mock := &IModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
